#! /bin/sh

: ${TT_S:=~/gitwk--bg/team_tools}
SAVEREPO=/nfs/anacode/mca/project-software-tracking/project-software.saveconf

$TT_S/saveconf/track-bigdir $SAVEREPO anacode  'linux*/anacode'
# precise-x86_64/anacode is under Git explicitly

$TT_S/saveconf/track-bigdir $SAVEREPO annohelp 'annohelp'
$TT_S/saveconf/track-bigdir $SAVEREPO zfish    '*/zfish'
