#!/bin/bash

set -eu

OUT=/tmp/otter_cron_build.out.$$
LOG=/tmp/otter_cron_build.log

set +e
"$@" >$OUT 2>&1
RESULT=$?
set -e

if [ $RESULT -ne 0 ]
    then
    echo "otter_cron_build failure or error output for the command:"
    echo "$@"
    echo
    echo "RESULT CODE: $RESULT"
    echo
    echo "OUTPUT:"
    cat "$OUT"
else
    cp -p "$OUT" "$LOG"
    echo "otter_cron_build success for the command:"
    echo "$@"
    echo
    echo Output is at: "$LOG"
fi

rm -f "$OUT"
