#! /bin/sh

TMPFILE=`mktemp /tmp/prove_quietly.XXXXXXXXXX` || exit 1
trap 'rm -f $TMPFILE' EXIT

# ensure PATH element, because cron's environment is stripped 
PATH=/software/bin:$PATH


# assume caller did 'cd' here
if prove -I cron/lib --norc -r -v cron/t/ >> $TMPFILE 2>&1; then
    :
#    echo OK
else
    echo Tests failed
    cat $TMPFILE
fi

#   http://github.com/apenwarr/cron2rss would be better
