#!/usr/local/bin/perl -Tw

use strict;
use warnings;

use DBI;
use CGI;
# use CGI::Carp qw(fatalsToBrowser);
use JSON();

my $cgi = CGI->new;
my $json = JSON->new;

my $db = $cgi->param("db");
my $dbh =
    DBI->connect("DBI:mysql:host=otterlive;port=3324;database=${db}",
                 "ottadmin", "lutralutra",
                 { RaiseError => 1, AutoCommit => 0 });
my $db_selection =
    $dbh->selectall_arrayref(<<'QUERY');
select count(*)
from ( select 1
       from exon e
       where e.is_current
       group by e.seq_region_id, e.stable_id
       having count(*) > 1
       ) dups
QUERY
$dbh->disconnect;

print $cgi->header("text/plain"), $json->encode($db_selection);
