#!/usr/local/bin/perl -Tw

use strict;
use warnings;

#use CGI::Carp qw(fatalsToBrowser);
BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }

use OtterWeb 'otterlive_dbh';
use CGI;
use JSON();

my $cgi = CGI->new;
my $json = JSON->new;

my $db = $cgi->param("db");
my $dbh = otterlive_dbh($db);
my $db_selection =
    $dbh->selectall_arrayref(<<'QUERY');
select count(*)
from ( select 1
       from exon e
       where e.is_current
       group by e.seq_region_id, e.stable_id
       having count(*) > 1
       ) dups
QUERY
$dbh->disconnect;

print $cgi->header("text/plain"), $json->encode($db_selection);
