#!/usr/local/bin/perl -Tw

use CGI::Carp qw( fatalsToBrowser );

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw( core bioperl123 ensembl70 otter76 );
use SangerWeb;

use YAML qw( Dump );

die Dump(\@INC);
