#! /bin/sh

_do_build() {
    local build_dir gitsrc

    build_dir="$( mktemp -d -t otterlace_build.zircon.XXXXXX )" || \
        bail "Failed to mktemp -d"

    gitsrc="$( anacode_source_repo --isclean --purpose otterlace_build,build_lib__zircon zircon )" || bail "Can't get zircon gitsrc"
    git clone -q "$gitsrc" "$build_dir" &&
    (
        cd "$build_dir" &&
        git checkout -qb _build "$src_version" &&
        (echo Zircon is; git log -1 | sed -e 's/^/    /') &&
        perl Makefile.PL INSTALL_BASE="${install_dir}" \
            INSTALLMAN3DIR=none &&
        make &&
        make test &&
        make install &&
        rm -rf -- "$build_dir" &&
        true ) &&
    true
}

install_dir="$1"
src_version=$2

# shared config and functions
. "$( dirname "$0" )/_otterlace.sh" || exit 1

[ -d "$install_dir" ] && [ -n "$src_version" ] || \
    bail "Syntax: _anacode_build_lib__zircon <install_dir> <src_version>

bad args
  $*"
_do_build
