#! /bin/sh

# _rackmac_copy_dmg <major.minor>
#
#   Transfer a built image to the FTP site.
#   Does not update any symlinks.

set -e
. "$( dirname "$0" )/_otterlace.sh" || exit 1

REL=$1
RACKMAC=otter@anacodeosx # match otterlace/release/scripts/MacOS/rsync_git_repos.sh

looks_like_version "$REL" || bail "Syntax: $0 <xx.yy>"

[ $(uname) = 'Linux' ] || bail "Run this from a Linux server,
 not the MacOS host (which has no access to the FTP site NFS home)"


# Workstation side
FTPROOT=~ftp/pub/anacode/otterlace
FTPDIR=$FTPROOT/release_$REL
echo Will take $FTPDIR from build in $RACKMAC:

[ -d $FTPROOT ] || bail "Cannot see $FTPROOT/"
if [ -d $FTPDIR ]; then
    echo "$FTPDIR exists already" >&2
    exit 9
fi

# mktemp -t : deprecated in GNU coreutils mktemp, but the only option
# in MacOS' OpenBSD version
XFERDIR=$( mktemp -t -d mac-rel$REL.XXXXXX )
chgrp -v anacode $XFERDIR
chmod -v 0775 $XFERDIR

scp -p \
    $RACKMAC:Otter/Dist/otterlace_mac_intel-$REL.dmg \
    $XFERDIR/

mv -v $XFERDIR $FTPDIR

printf "\n\n You update the symlink?\n"
ls -lrt --color $FTPROOT | sed -e 's/^/    /'

printf "\n\n maybe with one of\n    ln -snvf release_%s %s/%s\n    ln -snvf release_%s %s/%s\n\n" \
    "$REL" "$FTPROOT" TEST "$REL" "$FTPROOT" CURRENT

echo "Then wait for sync to ftp site"
