#!/bin/bash


# TO DO

# Install the server-side data files (which are allegedly managed in
# the ace_skeleton CVS repository).

# Locking.  But is this possible when the files we are changing are
# NFS-mounted?  Maybe ssh to a designated lock host and lock a local
# file?

# / TO DO


# NB

# We must build the binary XRemote module with the same version of
# Perl that our scripts use, because binary modules are installed to
# version-dependent locations.  Therefore we start the $PATH with
# (location of preferred Perl).

# But Perl will try to build the binary XRemote module with the same
# version of gcc that it was built with, which is not the version of
# gcc on modern hosts.  Therefore we set CC and LD to gcc, so that
# Perl will use the local gcc.

# / NB



# Process commandline args & optional variables passed in environment.
# May chdir un-scoped, or exit
get_opts_inputvars() {
    # zmap_trees, zmap_build, ensembl_otter_root : not local
    local sw

    while [[ $# > 0 ]]; do
        case "$1" in
            -h | --help) show_help_exit ;;
            --) shift
                break ;;
            --show-path)
                # this is here to assist debugging of problems-finding-self
                printf "PATH is now\n    %s\n" \
                    "$( echo $PATH | sed -e 's/:/\n    /g' )"
                exit 0 ;;
        esac
        shift
    done

    # Inner otterlace_client_install() runs needs one build directory,
    # passed in by otterlace_install_all .  Already in $zmap_build.

    # Outermost otterlace_install_all() run accepts multiple ZMap
    # build trees.  Store in $zmap_trees.
    #
    # Assume it is a space-separated list of directories containing no
    # funnychars.
    zmap_trees="$*"
    if [ -z "$otterlace_client_host" ]; then
        # we are not doing otterlace_client_install

        if [ -n "$zmap_build" ] && [ -z "$zmap_trees" ]; then
            zmap_trees="$zmap_build"
            unset zmap_build
            echo ' [W] manual $zmap_build override is deprecated, commit here if you still need it' >&2
            sleep 1
        fi

        [ -z "$zmap_trees" ] && show_help_exit
    fi


    if [ -n "$ensembl_otter_root" ]
    then
        cd "$ensembl_otter_root"
    else
        ensembl_otter_root="$( pwd )"
    fi
}

show_help_exit() {
    printf "Usage: %s [ options ] <zmap_build_dir>*

 This is %s

 Default is to build the Otter Server, and the internal Linux clients
 to /software/anacode .  This requires one ZMap build directory, from
 which the correct Otterlace build host(s) are looked up in
 build-config.yaml .

 Multiple ZMap builds may be given, normally during OS transition.
 Doing this adds extra build hosts.

 Options:

    --help | -h		Show this help

 Currently configured build hosts:

%s

" "$( basename "$0" )" "$thisprog" "$( _otterlace_build_config.pl -list 2>&1 )" >&2
    exit 1
}


# Set environment variables about self, umask.  These don't take
# parameters and are needed early (during get_opts_inputvars)
setup_self_globals() {
    # shared config and functions
    . "$( dirname "$0" )/_otterlace.sh" || exit 1

    osname="$( uname -s )"

    case "$osname" in
        Darwin)
            # Assume for now that PATH already contains the correct container, inc. perl
            export PATH=$PATH:$dist_scripts
            ;;

        *)
            export PATH=/software/perl-5.12.2/bin:/bin:/usr/bin:/usr/local/bin:$dist_scripts
            # XXX: insertion of a Perl build in PATH should probably be under control of something like otter_ipath_get,
            # and should from there be replicated to the otterlace wrapperfile (and any other built component running under Perl, probably via $PATH),
            # t/swac_stopwords.t will be failing while this is here...
            ;;
    esac

    export LD_LIBRARY_PATH=
    umask 002 # NB: running over ssh can set a surprising umask
}

# Set some environment variables, global variables for the script
setup_globals() {

    config_get version_major
    config_get version_minor
    config_get client_ensembl_version
    config_get track

    case "$track" in
        live) remove_existing_directories=false ;;
        *)    remove_existing_directories=true  ;;
    esac
    check_remove_existing_directories=true

    if [ -n "$version_minor" ]
    then
        # (already tagged by otterlace_release_tag)
        version="${version_major}.${version_minor}"
        cvs_humpub_release="humpub-release-${version_major}-${version_minor}"
    else
        # (ensembl-otter dev branch)
        version="$version_major"
        cvs_humpub_release="HEAD"
    fi

    # sanity check
    if [ -z "$version" ]
    then
        echo "error: the otterlace version is not set" >&2
        exit 1
    fi

    # EXTERNAL PARAMETERS
    : ${build_log:=/nfs/anacode/otterlace/ensembl_otter_build_log.txt}
    anacode_cvsroot=:ext:cvs.internal.sanger.ac.uk:/repos/cvs/anacode
    ensembl_cvsroot=:ext:cvs.sanger.ac.uk:/cvsroot/ensembl
    # / EXTERNAL PARAMETERS

    otter_ipath_get otter_home


    ensembl_cvs_flags="-r branch-ensembl-${client_ensembl_version}"
    # (ensembl libs on the server are provided by the web team)
}


with_new_directory() {
    local dir command
    dir="$1"
    command="$2"
    shift 2
    if [ -e "$dir" ] ; then
        if $check_remove_existing_directories &&
            ! $remove_existing_directories
        then
            echo "error: directory '${dir}' already exists, refusing to remove it" >&2
            return 1
        else
            write_build_log_entry --level deleting_old --dir "$dir"
            rm -rf -- "$dir"
        fi
    fi &&
    mkdir -v -p -- "$dir" &&
    chgrp -v anacode "$dir" &&
    chmod -v g+s "$dir" &&
    "$command" "$dir" "$@"
    status=$?
    echo " [i] with_new_directory: $command returned $status"
    chmod -R ug+rw "$dir" &&
    ( exit "$status" )
}

git_cache_create() {
    local install_dir
    install_dir="$1"

    # we create the cache using the modules in the git repository and
    # test by dumping the cache using the modules in the installation
    # directory

    perl -I"${ensembl_otter_root}/modules" -MBio::Otter::Git \
        -e 'Bio::Otter::Git->_create_cache(@ARGV);' "$install_dir" &&
    perl -I"$install_dir" -MBio::Otter::Git \
        -e 'Bio::Otter::Git->dump;' &&
    /bin/true
}

otterlace_script_vars_update() {
    (
        otter_ipath_get SUBST_anasoft    swac
        otter_ipath_get SUBST_OTTER_HOME otter_home
        export SUBST_version="$version"
        export SUBST_anasoft SUBST_OTTER_HOME
        perl -i -pe '
 if (!$finished && /^(\w+)=$/) {
   $v=$ENV{"SUBST_$1"};
   die qq{No value for "$1"} unless defined $v;
   chomp;
   $_ .= qq{"$v"\n};
   $substs ++;
 } elsif (/^\s*(#|$)/) {
 } elsif ($substs) {
   $finished = 1;
 }' "$1"
        )
}



otterlace_server_install_modules() {
    local install_dir source_dir
    install_dir="$1"
    source_dir="${ensembl_otter_root}/modules/Bio"
    cp -r "$source_dir" "$install_dir" &&
    git_cache_create "$install_dir" &&
    /bin/true
}

otterlace_server_install_cgi() {
    local install_dir source_dir
    install_dir="$1"
    source_dir="${ensembl_otter_root}/scripts/apache"
    cp -r "$source_dir"/* "$install_dir" &&
    /bin/true
}

otterlace_server_install() {
    local web_lib web_cgi check_remove_existing_directories
    echo ""
    echo "installing server"
    otter_ipath_get web_lib
    otter_ipath_get web_cgi
    check_remove_existing_directories=false
    echo "installing server: perl modules" &&
    with_new_directory "$web_lib" otterlace_server_install_modules &&
    echo "installing server: CGI scripts" &&
    with_new_directory "$web_cgi" otterlace_server_install_cgi &&
    write_build_log_entry --level server \
        --lib "$web_lib" \
        --cgi "$web_cgi" &&
    /bin/true
}



otterlace_client_install_perl_modules() {
    local install_dir
    install_dir="$1"

    echo &&
    echo "installing perl modules" &&

    ( cd "$install_dir" &&

        cvs -Q -f -d "$ensembl_cvsroot" \
            checkout -P $ensembl_cvs_flags \
            ensembl/modules &&

        cvs -Q -f -d "$ensembl_cvsroot" \
            checkout -P $ensembl_cvs_flags \
            ensembl-variation/modules &&

        cvs -Q -f -d "$anacode_cvsroot" \
            checkout -P -r "$cvs_humpub_release" \
            PerlModules/Hum &&

        cvs -Q -f -d "$ensembl_cvsroot" \
            checkout -P -r "$cvs_humpub_release" \
            ensembl-analysis/modules &&

        mkdir -p -- ensembl-otter &&
        cp -r \
            ${ensembl_otter_root}/{modules,scripts,tk} \
            ensembl-otter &&

        /bin/true ) &&

    git_cache_create "${install_dir}/ensembl-otter/modules" &&

    /bin/true
}

otterlace_client_install_scripts() {
    local install_dir
    install_dir="${1}/bin"

    mkdir -p -- "$install_dir" &&
    cp -- ${ensembl_otter_root}/scripts/client/* "$install_dir" &&
    /bin/true
}

otterlace_client_install_zmap() {
    local install_dir bin_dir build_dir
    install_dir="$1"
    bin_dir="${install_dir}/bin"
    build_dir="/tmp/otterlace_xremote_build/$$"
    rm -rf -- "$build_dir" &&
    mkdir -p -- "$build_dir" &&
    ( cd "$build_dir" &&
        cp -r -- "${zmap_build}/ZMap/src/perl/X11-XRemote-0.01" . &&
        cd X11-XRemote-0.01 &&
        perl Makefile.PL \
            PREFIX=${install_dir} \
            CC=gcc \
            LD=gcc \
            --with-zmap-libs "${zmap_prefix}/lib" \
            --with-zmap-inc  "${zmap_prefix}/include" \
            --with-symbols \
            &&
        make &&
        make test &&
        make install &&
        rm -rf -- "$build_dir" &&
        /bin/true ) &&
    mkdir -p -- "$bin_dir" &&
    cp -- ${zmap_prefix}/bin/* "$bin_dir" &&
    cp -r -- "${zmap_prefix}/share" "$install_dir" &&
    /bin/true
}

otterlace_client_install_client() {
    local install_dir
    install_dir="$1"
    otterlace_client_install_perl_modules "$install_dir" &&
    otterlace_client_install_scripts      "$install_dir" &&
    otterlace_client_install_zmap         "$install_dir" &&
    /bin/true
}

otterlace_client_install() {
    local arch
    # not local: zmap_prefix
    arch="$( uname -m )"

    echo ""
    echo "  client install"
    echo "  intended host: ${otterlace_client_host}"
    echo "  host name: $( hostname )"
    echo "  arch: ${arch}"
    echo "  distro version: $( lsb_release -sc || echo 'no release codename' )"

    # zmap_prefix is only meaningful during a client install
    zmap_prefix="${zmap_build}/Linux_$arch"
    [ -d "$zmap_prefix" ] || bail "error: client install for ${arch} aborted: the ZMap directory ${zmap_prefix} is missing or invalid"

    echo &&
    echo "removing old otterlace installation" &&
    with_new_directory "$otter_home" otterlace_client_install_client &&
    if wrapperfile_outside_otterdir; then
        # support versions pre-58 : wrapperfile in /sw/ac/bin
        otterlace_template=dist/templates/otterlace
        [ -f "$otterlace_template" ] || bail "For version=$version wrapperfile_outside_otterdir is true; expected $otterlace_template to exist"
        otter_ipath_get otterlace_local wrapperfile
        cp -- "$otterlace_template" "$otterlace_local" &&
        otterlace_script_vars_update "$otterlace_local" &&
        chmod -v 775 "$otterlace_local" &&
        /bin/true
    else
        otterlace_script_vars_update "${otter_home}/bin/otterlace_env.sh" &&
        sed -i \
            -e '/^otterlace_installed=/s/=.*$/=true/' \
            "${otter_home}/bin/otterlace" \
            &&
        /bin/true
    fi &&
    (
        zmap="$(     "${otter_home}/bin/zmap"   --version 2>&1 )"
        seqtools="$( "${otter_home}/bin/blixem" --version 2>&1 )"
        zmap_prefix_real="$( readlink -e "$zmap_prefix" || echo ?? )"
        if [ "$zmap_prefix" = "$zmap_prefix_real" ]; then
            is_ln=""
        else
            is_ln=" -> $zmap_prefix_real"
        fi
        write_build_log_entry --level client \
            --zmap_prefix "$zmap_prefix$is_ln" \
            --zmap     "$zmap"     \
            --seqtools "$seqtools"
        ) &&
    echo " [i] finished otterlace_client_install for $otterlace_client_host" &&
    /bin/true
}

otterlace_install_all() {
    local env_cmd ssh_cmd

    if [ -n "$client_build_hosts" ]; then
        echo ' [W] $client_build_hosts override can (currently) restrict the set of build hosts, but not replace them' >&2
        sleep 1
        # else we would have a local variable
    else
        # choose build hosts to match our zmap build(s)
        client_build_hosts="$( _otterlace_build_config.pl $zmap_trees )" \
            || bail "Bad zmap builds?  No build hosts - no build"
    fi

    otterlace_server_install &&
    for host in $client_build_hosts; do
        export zmap_build="$( _otterlace_build_config.pl -host $host $zmap_trees )" \
            || bail "No zmap_build for $host ..?"
        env_reexport env_cmd \
            otter_swac otter_nfswub otter_suffix \
            ensembl_otter_root zmap_build build_log
        unset zmap_build

        ssh_cmd="ssh -A $host  env $env_cmd otterlace_client_host=$host  $0"
        printf "\n== Client build: $ssh_cmd\n"
        $ssh_cmd || write_build_log_entry --level client --failed "returned $?"
    done

    write_build_log_entry --level all
}

write_build_log_entry() {
    local date commit

    date="$( date +'%Y/%m/%d-%H:%M:%S' )"
    commit="$( git rev-list --max-count=1 HEAD )"
    if [ -z "$commit" ]
    then
        commit="NONE"
    fi

    otterlace_build_log_entry \
        --date     "$date"     \
        --version  "$version"  \
        --track    "$track"    \
        --commit   "$commit"   \
        --builder  "$thisprog" \
        --user     "$( whoami )"      \
        --host     "$( hostname -s )" \
        "$@"                   \
        | tee --append -- "$build_log" | sed -e 's/^/\tL:/'
}



setup_self_globals
get_opts_inputvars "$@"
setup_globals
# echo "otter_home = '${otter_home}'" ; exit # uncomment to test


if [ -n "$otterlace_client_host" ]
then
    otterlace_client_install
else
    otterlace_install_all
fi
