#!/bin/bash


# This updates the symbolic links for a given track across all build hosts.


. "$( dirname "$0" )/_otterlace.sh" || exit 1

DRYRUN=''
mode='link'

while [ $# -gt 0 ] && [ "${1:0:1}" = "-" ]; do
    sw=$1
    shift
    case $sw in
        -h | --help)
            bail "Syntax: $0 [ -n | --dry-run ] [ -d | --delete ] <track>

 This should be run from an ensembl-otter working copy
 which is up-to-date on the appropriate branch
 (unless deleting)." ;;
        -n | --dry-run)
            echo "(dry run mode)" >&2
            dryrun='-n'
            DRYRUN='echo :' ;;
        -d | --delete)
            mode='delete' ;;
        *) bail "Unknown option $sw" ;;
    esac
done

[ "$#" = 1 ] || bail "Syntax: $0 [ -n | --dry-run ] [ -d | --delete ] <track>"
track="$1"

client_build_hosts="$( _otterlace_build_config.pl $track )" \
    && [ -n "$client_build_hosts" ] \
    || bail "Bad track? No client build hosts."

case $track in
    test)
        ftp_track=TEST ;;
    live)
        ftp_track=CURRENT ;;
esac

# Not quoted to allow ~ftp expansion
ftp_base=~ftp/pub/anacode/otterlace

do_link() {

    for host in $client_build_hosts; do
        remote_cmd="cd $PWD && otterlace_symlink_update $dryrun $track"
        ssh_cmd="ssh -A $host $remote_cmd"
        echo "== Host '$host':"
        $ssh_cmd
    done

    full_version=$( full_version )

    if [ -n "$ftp_track" ]; then
      echo "== FTP:" && $DRYRUN ln -vnfs --  "release_$full_version" "$ftp_base/$ftp_track"
    fi

}

do_delete() {

    [ "$track" = "live" ] && bail "delete not supported for 'live' track"

    otter_ipath_get holtdir

    for host in $client_build_hosts; do
        remote_cmd="cd $PWD && $DRYRUN rm $holtdir/otter_${track}"
        ssh_cmd="ssh -A $host $remote_cmd"
        echo "== Host '$host':"
        $ssh_cmd
    done

    if [ -n "$ftp_track" ]; then
      echo "== FTP:" && $DRYRUN rm "$ftp_base/$ftp_track"
    fi

}

case $mode in
    link)
        do_link
        ;;
    delete)
        do_delete
        ;;
    *)
        bail "Unknown mode $mode"
        ;;
esac

exit
