#!/usr/bin/env perl

use strict;
use warnings;

use YAML();

my $log_entry = { };

while (my ($k, $v) = splice @ARGV, 0, 2) {
    $k =~ s/^--?//;
    $log_entry->{$k} = $v;
}
die "Syntax: $0 [ <--key> <value> ]+\n"
  if !%$log_entry || grep { !defined } values %$log_entry;

print YAML::Dump($log_entry);
