#!/bin/bash

# Bumps the version numbers which are stored as files in
# ensembl-otter/dist/conf/ .
#
# Creates tags in Git and CVS modules, acting (more or less) directly
# on the central repositories.  That means you can run the current
# devel tagging script against an existing release branch, treating
# the release as data.
#
# Leaves repositories in a state from which you could VCS-export code
# to build a specific release ($MAJOR-$MINOR)


# The plan for bumping the major version:
#
#   we are on "master" branch, doing development
#
#   minor version number is not set
#
#   on the new release branch,
#     keep the old major version,
#     have a minor version bump to .01
#     record the current zircon commitid
#       from ref named in on master:dist/conf/zircon
#       into dist/conf/zircon
#       and push a tag for that
#
#   on the master branch,
#     keep minor version unset
#     have a major version bump
#     tag it as the next -dev, for the benefit of Bio::Otter::Git
#
# We are then ready for new release & dev builds


# The plan for bumping the minor version:
#
#   start on the "master" branch
#
#   we must obtain the current release
#     subtract one from the apparent version_major
#     checkout this release branch
#
#   on the existing release branch,
#     minor version bump
#     (could update zircon version, if we had a well-defined process for that)


# CVSROOTs need to be suitable for use both with "cvs -d" and scp
ensembl_cvs_repo=cvs.sanger.ac.uk:/cvsroot/ensembl
anacode_cvs_repo=cvs.internal.sanger.ac.uk:/repos/cvs/anacode
ensembl_otter_git_repo=git:/repos/git/anacode/ensembl-otter
zircon_git_repo=${ANACODE_ZIRCON:-git:/repos/git/anacode/zircon}

. "$( dirname "$0" )/_otterlace.sh" || exit 1


# Dummy repositories for script testing.
_create_dummy_repos_cvs() {
    dummies="$( mktemp -t -d DUMMY_REPOS.XXXXXX )" || bail "Failed to mktemp -d"
        # Serious because caller does not want to do real operations

    printf "\n*** Creating and running with dummy repos,\n    dummies=%s\n    these will NOT be cleaned up\n    you can use them again by setting the variable and flag\n\n" "$dummies"

    # Make fake repos
    #  ens-ott is deliberately != ensembl-otter
    #  humscripts is a canary module, should not be changed
    #  ensembl-analysis is a copy of the real module, transplanted into a fresh CVS repo
    (
        set -e
        cd "$dummies"
        # set -e, cd : local to the ( ... )

        mkdir -p $dummies/{ensembl/ensembl-analysis,anacode}
        echo ': ensembl-otter'
        git clone -q --bare "$ensembl_otter_git_repo" ens-ott.git
        echo ': zircon'
        git clone -q --bare "$zircon_git_repo" zircon.git

        echo ': anacode (part)'
        scp -rpq ${anacode_cvs_repo}/{CVSROOT,PerlModules,humscripts} "$dummies/anacode"

        # avoid copying ensembl's CVSROOT, it has huge history
        cvs -d "$dummies/ensembl" init
        echo ': ensembl-analysis'
        scp -rpq ${ensembl_cvs_repo}/ensembl-analysis "$dummies/ensembl/"

        # CVS repos use separate LockDir, which we don't have or want
        perl -i~ -pe 's{(LockDir=.*)}{#### $1}' $dummies/anacode/CVSROOT/config
        )
}

_use_dummy_repos_cvs() {
    if [ -z "$dummies" ]; then
        _create_dummy_repos_cvs || bail "Create dummy repos failed"
    elif [ -d "$dummies/ens-ott.git" ]; then
        printf "\n*** Running with existing dummy repos in %s\n" "$dummies"
    else
        bail "No dummy repos at $dummies/ens-ott.git ?"
    fi

    # Replace the "upstream" repositories, so we can perform real VCS
    # operations on them.
    set -x
    ensembl_cvs_repo="$dummies/ensembl"
    anacode_cvs_repo="$dummies/anacode"
    ensembl_otter_git_repo="$dummies/ens-ott.git"
    zircon_git_repo="$dummies/zircon.git"
    set +x
}


sanity_check_version_minor_is_null() {
    # This runs on master of a fresh checkout.  Even when we are about
    # to bump the minor version on an existing release branch.
    sanity_check_version_major_not_null
    [ -z "$( config version_minor )" ] || {
        echo "version_minor '${version_minor}' is not null"
        echo "on master branch? this is weird, cannot proceed with major version bump"
        echo "please fix something and try again"
        # sanity check failed - bail
        exit 1
    } >&2
}

sanity_check_version_major_not_null() {
    # Runs both on master and release branches, at different times
    [ -n "$( config version_major )" ] || {
        echo "version_major is null - weird"
        echo "do we have dist/conf/ on this branch?"
        git branch -v
        exit 1
    } >&2
}

set_variables_bumpmajor() {
    # these variables intentionally not local

    set_variables_bumpminor
    version_major_new="$( printf "%02d" "$(( 10#$version_major + 1 ))" )" || bail "math error"
    dev_tag="humpub-release-${version_major_new}-dev"
}

set_variables_bumpminor() {
    # these variables intentionally not local
    sanity_check_version_major_not_null

    config_get version_major
    config_get old_version_minor version_minor
    version_minor="$( printf "%02d" "$(( 10#$old_version_minor + 1 ))" )" || bail "math error"
    # this works on master "56"."" -> "56"."01" for bumpmajor,
    # and on a release branch "56"."01" -> "56"."02"

    release_branch="humpub-branch-${version_major}"
    release_tag="humpub-release-${version_major}-${version_minor}"
}

# changes $PWD
# sets global variables
git_update() {
    git clone -q -b master "$ensembl_otter_git_repo" ensembl-otter &&
    cd ensembl-otter &&
    sanity_check_version_minor_is_null &&

    if [ "$do_op" = "major" ]; then
        do_bumpmajor
    elif [ "$do_op" = "minor" ]; then
        do_bumpminor
    else
        echo "Puzzled: $do_op" >&2
        false
    fi &&

    git push ${dryrun:+-n} origin master "$release_tag" $dev_tag "$release_branch" &&
    # pushing master is not always necessary, but a no-op is safe.
    #
    # $dev_tag may be empty, in which case it is not pushed (no
    # quotes, else we push "" which breaks)

    true
}

do_bumpmajor() {
    set_variables_bumpmajor &&

    # release branch and tags
    git checkout -b "$release_branch" &&
    config_set version_minor "$version_minor" &&
    config_set zircon "$( mk_zircon_version )" &&
    git commit -a -m "$( printf "New release branch.\n\nNext release will be ${release_tag};\nGenerated by %s\n" "$thisprog" )" &&
    git tag "$release_tag" &&
    git_show_maybe &&
    git_listrefs_maybe &&
    config_show_maybe &&

    # version bump
    git checkout master &&
    $dist_scripts/otterlace_version_major_set "$version_major_new" &&
    git tag "$dev_tag" &&
    git_show_maybe &&
    config_show_maybe &&

    true
}

# May update $bumprel
do_bumpminor() {
    local dev_major
    if [ "$bumprel" = "last" ]; then
        config_get dev_major version_major
        bumprel="$( printf "%02d" "$(( 10#$dev_major - 1 ))" )" || bail "math error"
        echo " : Current development is v$dev_major"
    fi

    echo ' : Did nothing to dist/conf/zircon'

    git checkout "humpub-branch-$bumprel" &&
    echo " : Using release branch v$bumprel" &&

    set_variables_bumpminor &&

    # release tag
    config_set version_minor "$version_minor" &&
    git commit -a -m "$( printf "New release tag %s\n\nGenerated by %s\n" "$release_tag" "$thisprog" )" &&
    git tag "$release_tag" &&
    git_show_maybe &&
    git_listrefs_maybe &&
    config_show_maybe &&
    true
}


mk_zircon_version() {
    local zircon_version
    config_get zircon_version zircon
    (
        cd "$tmp_dir" &&
        git clone -q "$zircon_git_repo" zircon &&
        cd zircon &&
        if git tag -l | grep -qE "^$release_tag\$"; then
            # Tag exists
            :
        else
            git tag -a -m "Tag made at current $zircon_version for use in Otterlace,
(FYI.  dist/conf/zircon defines it from the other end.)" \
                "$release_tag" "$zircon_version" &&
            git push ${dryrun:+-n} --tags
            # It's not clear we need to keep these tags.  We could
            # delete them or stop creating them.  They provide a
            # putative idempotence which a successful run of this
            # script will not use.
        fi &&
        git log -1 --format=%H "$release_tag"
    ) &&
    true
}


# On one CVS repo, tag the release
# and if we did set_variables_bumpmajor,
#   also label the branch at that point
cvs_update_repo() {
    local repo module
    repo="$1"
    module="$2"
    if [ -n "$version_major_new" ]; then
        ${dryrun:+echo DRYRUN:} cvs -d "$repo" -q rtag    -rHEAD              "$release_tag"    "$module" &&
        ${dryrun:+echo DRYRUN:} cvs -d "$repo" -q rtag -b -r"$release_tag"    "$release_branch" "$module"
    else
        ${dryrun:+echo DRYRUN:} cvs -d "$repo" -q rtag    -r"$release_branch" "$release_tag"    "$module"
    fi &&
    true
}

cvs_update() {
    cvs_update_repo "$anacode_cvs_repo" PerlModules      &&
    cvs_update_repo "$ensembl_cvs_repo" ensembl-analysis &&
    true
}


# Sets variables.  May exit.
parse_switches() {
    local sw
    while [ $# -gt 0 ]; do
        sw=$1
        shift
        case $sw in
            --major) _setop major   ;;
            --minor) _setop minor
                bumprel=last
                case $1 in
                    [0-9][0-9] | [0-9][0-9][0-9] )
                        bumprel=$1
                        shift
                        ;;
                esac
                ;;
            -v | --verbose)  verbose=1      ;;
            -D | --dummy)    with_dummy=1   ;;
            -n | --dryrun)   dryrun=1       ;;
            -h | --help)
                show_syntax
                exit 0
                ;;
            *)
                bail "Unknown option '$sw', try -h"
                ;;
        esac
    done
}

_setop() {
    if [ -n "$do_op" ]; then
        bail "Already planning to do '$do_op', cannot also do '$1'"
    fi
    do_op=$1
}


show_syntax() {
    echo "Syntax: $0 [ -v ] [ -D ] [-n] < --major | --minor [NN] >"
    cat <<MSG

Necessary switches - one of

  --major      Tag new release branch and matching .01 minor release.

  --minor NN   Tag new minor release on the existing branch for major
               version NN.

  --minor      Tag new minor release on the latest release branch.
               Uses (current master's major release number) minus one.


Optional switches:

  -D
  --dummy    Make in TMPDIR some local CVS and Git repositories,
             and use these instead of the real ones.

  -n
  --dryrun   Perform noisy no-ops instead of VCS commands.

  -v
  --verbose  More noise


This is $thisprog

MSG
}


main() {
    local tmp_dir
#    echo "Doing these: do_op=$do_op bumprel=$bumprel verbose=$verbose dryrun=$dryrun with_dummy=$with_dummy"

    if [ -z "$do_op" ]; then
        echo "Missing a necessary option"
        show_syntax >&2
        return 4
    fi

    if $dist_scripts/git-is-synced; then
        echo "Your working copy is in sync.  It will be safe to pull after the bump."
    elif [ -n "$dryrun" ]; then
        echo "Your working copy is NOT in sync, but this is a dry run"
    else
        echo "Your working copy is NOT in sync.  Is this a good idea?" >&2
        return 3
    fi

    tmp_dir="$( mktemp -t -d "$( basename "$0" ).XXXXXX" )" || bail "mktemp failed"

    if [ -n "$with_dummy" ]; then
        _use_dummy_repos_cvs
    elif [ -n "$dummies" ]; then
        bail "Found dummies=$dummies but not given --dummy flag"
        # continuing is probably not what the caller expected
    fi

    ( cd "$tmp_dir" &&
        git_update &&
        cvs_update &&
        true ) &&

    if [ -n "$with_dummy" ]; then
        echo "# Would 'git pull -v' to your working copy here, but"
        echo "# we are using dummy repos so here is a dry-run fetch instead"
        echo "git fetch --dry-run $ensembl_otter_git_repo, as if from origin:"
        git fetch --dry-run $ensembl_otter_git_repo 'refs/heads/*:refs/remotes/origin/*' 'refs/tags/*:refs/tags/*'
        # The explicit tags fetch is redundant unless there are tags
        # which are not on branches, and is verbose because we dry-run
        echo "Or    (cd $ensembl_otter_git_repo; gitk --all &)"
    else
        ${dryrun:+echo DRYRUN:} git pull -v
    fi &&

    rm -rf -- "$tmp_dir" &&
    true # success
}


parse_switches "$@"

main
exit $?
