#!/bin/bash
# Bash for ${sub:st:s}, regexps, {brace,expansion}, ...


# TO DO

# Install the server-side data files (which are allegedly managed in
# the ace_skeleton CVS repository).

# Locking.  But is this possible when the files we are changing are
# NFS-mounted?  Maybe ssh to a designated lock host and lock a local
# file?

# / TO DO



# Process commandline args & optional variables passed in environment.
# May chdir un-scoped, or exit or exec
get_opts_inputvars() {
    # zmap_trees, zmap_build, ensembl_otter_root, client_build_hosts : not local
    # local_client_only : not local
    local sw opt

    while [[ $# > 0 ]] && [ "${1:0:1}" = "-" ]; do
        opt="$1"
        shift
        case "$opt" in
            -h | --help) show_help_exit "Help requested." ;;
            --) shift
                break ;;
            --show-path)
                # this is here to assist debugging of problems-finding-self
                printf "PATH is now\n    %s\n" \
                    "$( echo $PATH | sed -e 's/:/\n    /g' )"
                exit 0 ;;
            --hosts | -H)
                # this is a convenience option, so _otterlace_build_config.pl can remain "internal"
                exec _otterlace_build_config.pl -list ;;
            --server-only | -S)
                [ -n "$client_build_hosts" ] && bail "Was about to overwrite client_build_hosts='$client_build_hosts'"
                client_build_hosts=' '
                ;;
            --local-client-only | -L)
                [ -n "$otterlace_client_host" ] \
                    && bail "Was about to overwrite otterlace_client_host='$otterlace_client_host'"
                otterlace_client_host="$( hostname )"
                local_client_only=1
                ;;
            *)
                show_help_exit "Unknown option: $opt"
                ;;
        esac
    done

    [ "$client_build_hosts" = ' ' ] && [ -n "$local_client_only" ] && \
        show_help_exit "--server-only and --local-client-only are mutually exclusive."

    # Inner otterlace_client_install() runs needs one build directory,
    # passed in by otterlace_install_all .  Already in $zmap_build.

    # Outermost otterlace_install_all() run accepts multiple ZMap
    # build trees.  Store in $zmap_trees.
    #
    # Assume it is a space-separated list of directories containing no
    # funnychars.

    if [ -n "$local_client_only" ] && [[ $# > 1 ]]; then
        show_help_exit "--local-client-only mode takes only a single ZMap build."
    fi

    zmap_trees="$*"

    if [ -z "$otterlace_client_host" ] || [ -n "$local_client_only" ]; then
        # we are not doing inner otterlace_client_install() from otterlace_install_all()

        if [ -n "$zmap_build" ] && [ -z "$zmap_trees" ]; then
            zmap_trees="$zmap_build"
            unset zmap_build
            echo ' [W] manual $zmap_build override is deprecated, commit here if you still need it' >&2
            sleep 1
        fi

        [ -n "$zmap_trees" ] || [ "$client_build_hosts" = ' ' ] || show_help_exit "Doing client build, but have no zmap_trees."
    fi

    if [ -n "$local_client_only" ]; then
        zmap_build="$zmap_trees"
        unset zmap_trees
    fi

    if [ -n "$ensembl_otter_root" ]
    then
        cd "$ensembl_otter_root"
    else
        ensembl_otter_root="$( pwd )"
    fi

    # sanity check for the remote phases
    if [ -n "$otterlace_client_host" ] ||
        [ "$client_build_hosts" = ' ' ] ||
        ! [[ ~ =~ /nfs/ ]]; then
        # Probably OK, not a remote build
        :
    elif [[ "$ensembl_otter_root" =~ /(nfs|software|warehouse)/ ]] &&
        [[ "$zmap_trees" =~ /(nfs|software|warehouse)/ ]]; then
        # Probably OK, sources are remote
        :
    else
        printf "\n [W] Are we about to build remotely from local filesystem?\n\n   e-o = %s\n  zmap = %s\n     ~ = %s\n\n(wait 3 sec...)\n" \
            "$ensembl_otter_root" "$zmap_trees" ~ >&2
        sleep 3
    fi
}

show_help_exit() {
    local problem
    problem="$1"

    printf "Usage: %s [ options ] <zmap_build_dir>*

 This is %s

 (!) %s

 Default is to build the Otter Server, and the internal Linux clients
 to /software/anacode .  This requires one ZMap build directory, from
 which the correct Otterlace build host(s) are looked up in
 build-config.yaml .

 Multiple ZMap builds may be given, normally during OS transition.
 Doing this adds extra build hosts.

 Options:

    --help | -h			Show this help (and stop)
    --hosts | -H		Show build hosts list (and stop)

    --server-only | -S		Build Otter Server, but no clients

    --local-client-only | -L	Build Otter Client on this host

" "$( basename "$0" )" "$thisprog" "$problem" >&2
    exit 1
}


# Set environment variables about self, umask.  These don't take
# parameters and are needed early (during get_opts_inputvars)
#
# While doing this, identify the (same) Perl which Otterlace should
# use at runtime.
setup_self_globals() {
    # shared config and functions
    . "$( dirname "$0" )/_otterlace.sh" || exit 1

    osname="$( uname -s )"

    case "$osname" in
        Darwin)
            # Assume for now that PATH already contains the correct container, inc. perl
            export PATH=$PATH:$dist_scripts
            install_group="$( id -g -n )"
            otter_perl=perl_is_bundled # a magic word for otterlace_env.sh
            ;;

        *)
            # Assume PATH has /software/perl-$MUMBLE/bin from team_tools/bash_profile
            # We need to preserve that into otterlace_env.sh
            otter_perl="$( dirname $( which perl ))"
            export PATH=$otter_perl:/bin:/usr/bin:/usr/local/bin:$dist_scripts
            install_group="anacode"
            ;;
    esac

    export LD_LIBRARY_PATH=
    umask 002 # NB: running over ssh can set a surprising umask
}

# Set some environment variables, global variables for the script
setup_globals() {
    local found_perl

    found_perl="$( which perl )"
    if ! perl -M5.12.2 -e 1 || [ "$( dirname "$found_perl" )" = '/usr/bin' -a -z "$use_system_perl" ]; then
        bail "Think I have the wrong Perl ($found_perl)"
    fi

    if [ -z "$DISPLAY" ]; then
        # X11 display is unset or empty (cannot tell which)
        #
        # Ensure it is unset because, if it is merely empty then "ssh"
        # tries to forward it to the build host, which then tries to
        # use the tunnel and discovers it is broken.
        unset DISPLAY
    fi

    config_get version_major
    config_get version_minor
    config_get client_ensembl_version

    check_remove_existing_directories=true

    if [ -n "$version_minor" ]
    then
        # (already tagged by otterlace_release_tag)
        version="${version_major}.${version_minor}"
        cvs_humpub_release="humpub-release-${version_major}-${version_minor}"
    else
        # (ensembl-otter dev branch)
        version="$version_major"
        cvs_humpub_release="HEAD"
    fi

    # sanity check
    if [ -z "$version" ]
    then
        echo "error: the otterlace version is not set" >&2
        exit 1
    fi

    ### EXTERNAL PARAMETERS
    #

    : ${build_log:=/nfs/anacode/otterlace/ensembl_otter_build_log}
    # on some Macs and in VM, /nfs/anacode cannot be reached

    cvs_user="${cvs_user}${cvs_user:+@}" # append @ to cvs_user, else empty
    # cvs_user : when building in VM, real username is arbitrary and different

    #
    ### / EXTERNAL PARAMETERS

    # source code
    anacode_cvsroot=":ext:${cvs_user}cvs.internal.sanger.ac.uk:/repos/cvs/anacode"
    ensembl_cvsroot=":ext:${cvs_user}cvs.sanger.ac.uk:/cvsroot/ensembl"

    # Other values previously accepted
    #   ANACODE_ZIRCON    to source it from local git clone
    [ -n "$ANACODE_ZIRCON" ] && bail "Found ANACODE_ZIRCON=$ANACODE_ZIRCON but feature was withdrawn, please use anacode_source_repo(1) instead"

    # check early, else it will be too late
    [ -d "$build_log" ] && [ -w "$build_log" ] || \
        bail "build_log=$build_log: should be a writable directory (was a create/append-forever file, see RT#223520)"

    otter_ipath_get otter_home


    if [[ "${client_ensembl_version}" =~ ^[0-9]+$ ]]
    then
        # ordinarily just a verson number, so turn it into a tag
        ensembl_cvs_flags="-r branch-ensembl-${client_ensembl_version}"
    else
        # for anything else, we assume it's the whole tag
        ensembl_cvs_flags="-r ${client_ensembl_version}"
    fi
    # (ensembl libs on the server are provided by the web team)
}


with_new_directory() {
    local dir command
    dir="$1"
    command="$2"
    shift 2
    if [ -e "$dir" ] ; then
        if $check_remove_existing_directories && [ -n "$version_minor" ]
        then
            echo "error: directory '${dir}' already exists, refusing to remove it" >&2
            return 1
        else
            write_build_log_entry --level deleting_old --dir "$dir"
            rm -rf -- "$dir"
        fi
    fi &&
    mkdir -v -p -- "$dir" &&
    chgrp -v "${install_group}" "$dir" &&
    chmod -v g+s "$dir" &&
    "$command" "$dir" "$@"
    status=$?
    echo " [i] with_new_directory: $command returned $status"
    chmod -R ug+rw "$dir" &&
    ( exit "$status" )
}

git_cache_create() {
    local install_dir
    install_dir="$1"

    # we create the cache using the modules in the git repository and
    # test by dumping the cache using the modules in the installation
    # directory

    perl -I"${ensembl_otter_root}/modules" -MBio::Otter::Git \
        -e 'Bio::Otter::Git->_create_cache(@ARGV);' "$install_dir" &&
    perl -I"$install_dir" -MBio::Otter::Git \
        -e 'Bio::Otter::Git->dump;' &&
    true
}

otterlace_script_vars_update() {
    (
        otter_ipath_get SUBST_anasoft    swac
        otter_ipath_get SUBST_OTTER_HOME otter_home
        export SUBST_version="$version"
        export SUBST_otter_perl="$otter_perl"
        export SUBST_anasoft SUBST_OTTER_HOME
        perl -i -pe '
 if (!$finished && /^(\w+)=$/) {
   $v=$ENV{"SUBST_$1"};
   die qq{No value for "$1"} unless defined $v;
   chomp;
   $_ .= qq{"$v"\n};
   $substs ++;
 } elsif (/^(\w+)=.+/) {        # ignore lines already set by otterlace_client_edit_dist_macos()
 } elsif (/^\s*(#|$)/) {
 } elsif ($substs) {
   $finished = 1;
 }' "$1"
        )
}



otterlace_server_install_modules() {
    local install_dir source_dir
    install_dir="$1"
    source_dir="${ensembl_otter_root}/modules/Bio"
    cp -r "$source_dir" "$install_dir" &&
    git_cache_create "$install_dir" &&
    true
}

otterlace_server_install_cgi() {
    local install_dir source_dir
    install_dir="$1"
    source_dir="${ensembl_otter_root}/scripts/apache"
    cp -r "$source_dir"/* "$install_dir" &&
    true
}

otterlace_server_install() {
    local web_lib web_cgi check_remove_existing_directories
    echo ""
    echo "installing server"
    otter_ipath_get web_lib
    otter_ipath_get web_cgi
    check_remove_existing_directories=false
    echo "installing server: perl modules" &&
    with_new_directory "$web_lib" otterlace_server_install_modules &&
    echo "installing server: CGI scripts" &&
    with_new_directory "$web_cgi" otterlace_server_install_cgi &&
    write_build_log_entry --level server \
        --lib "$web_lib" \
        --cgi "$web_cgi" &&
    true
}



otterlace_client_install_perl_modules() {
    local install_dir
    install_dir="$1"

    echo &&
    echo "installing perl modules" &&

    ( cd "$install_dir" &&

        cvs -Q -f -d "$ensembl_cvsroot" \
            checkout -P $ensembl_cvs_flags \
            ensembl/modules &&

        if [ "${version_major}" -le 75 ]; then # ensembl-variation not required on client after v75
            cvs -Q -f -d "$ensembl_cvsroot" \
                checkout -P $ensembl_cvs_flags \
                ensembl-variation/modules
        fi &&

        cvs -Q -f -d "$anacode_cvsroot" \
            checkout -P -r "$cvs_humpub_release" \
            PerlModules/Hum &&

        mkdir -p -- ensembl-otter &&
        cp -r \
            ${ensembl_otter_root}/{modules,scripts,tk} \
            ensembl-otter &&

        true ) &&

    git_cache_create "${install_dir}/ensembl-otter/modules" &&

    true
}

otterlace_client_install_scripts() {
    local install_dir src_subdir
    install_dir="${1}/bin"
    src_subdir="scripts/client"
    [ -n "${2}" ] && src_subdir="scripts/${2}/client"

    mkdir -p -- "$install_dir" &&
    if [ -n "$( find ${ensembl_otter_root}/${src_subdir}/ -type f -print -quit )" ]; then
        cp -- ${ensembl_otter_root}/${src_subdir}/* "$install_dir"
    else
        # no files
        true
    fi &&
    true
}

otterlace_client_install_zmap() {
    local install_dir bin_dir
    install_dir="$1"
    bin_dir="${install_dir}/bin"
    mkdir -p -- "$bin_dir" &&
    if [ -f dist/conf/zircon ]; then
        # Zircon is required any time since 3ab9871550f4235fa8eb2ad0a34714ac8cc75f7e e-o
        # build_lib__zircon will die, until 982293f5 or 2281067c e-o
        build_lib__zircon
    fi &&
    cp -- ${zmap_prefix}/bin/{zmap,tace,sgifaceserver,blixemh,dotter,belvu} "$bin_dir" &&
    cp -r -- "${zmap_prefix}/share" "$install_dir" &&
    true
}


# We build with the same version of Perl that our scripts use.  This
# was because binary modules are installed to version-dependent
# locations.  If we should need to go there again, check vc history!
build_lib__zircon() {
    local build_dir gitsrc zircon_version

    config_get zircon_version zircon
    build_dir="$( mktemp -d -t otterlace_build.zircon.XXXXXX )" || \
        bail "Failed to mktemp -d"

    gitsrc="$( anacode_source_repo --isclean --purpose otterlace_build,build_lib__zircon zircon )" || bail "Can't get zircon gitsrc"
    git clone -q "$gitsrc" "$build_dir" &&
    (
        cd "$build_dir" &&
        git checkout -qb _build "$zircon_version" &&
        (echo Zircon is; git log -1 | sed -e 's/^/    /') &&
        perl Makefile.PL INSTALL_BASE="${install_dir}" \
            INSTALLMAN3DIR=none &&
        make &&
        make test &&
        make install &&
        rm -rf -- "$build_dir" &&
        true ) &&
    true
}

otterlace_client_edit_dist_macos() {
    local install_dir macos_dist_dir plist_buddy info_plist
    install_dir="$1"

    macos_dist_dir="${install_dir}/ensembl-otter/scripts/MacOS/dist"
    plist_buddy="/usr/libexec/PlistBuddy"
    info_plist="${macos_dist_dir}/Info.plist"

    # These are edited with version information here since we know
    # what version we are building, but they are copied into place
    # outside the 'otter_swac' tree by the calling script,
    # MacOS/install_otterlace.sh, which knows where to put them.

    # MacOS-specific startup script, chains to standard otterlace script
    otterlace_script_vars_update "${macos_dist_dir}/otterlace" &&

    # Info.plist file contains version number
    "${plist_buddy}" -c "Set :CFBundleShortVersionString ${version}" "${info_plist}" &&
    "${plist_buddy}" -c "Set :CFBundleVersion            ${version}" "${info_plist}" &&

    # Copy out setting of OTTER_HOME and modify anasoft
    # in standard otterlace_env.sh script
    sed -i.bak \
        -e '/^OTTER_HOME=/s/^/#/' \
        -e '/^anasoft=/s/$/"$OTTER_SWAC"/' \
        "${install_dir}/bin/otterlace_env.sh" \
        &&
    rm "${install_dir}/bin/otterlace_env.sh.bak" &&

    true
}

otterlace_client_install_os() {
    local install_dir
    install_dir="$1"

    case "$osname" in
        Darwin)
            otterlace_client_install_scripts "$install_dir" "MacOS" &&
            otterlace_client_edit_dist_macos "$install_dir"         &&
            true
            ;;
        *)
            true
            ;;
    esac
}

otterlace_client_install_client() {
    local install_dir
    install_dir="$1"
    otterlace_client_install_perl_modules "$install_dir" &&
    otterlace_client_install_scripts      "$install_dir" &&
    otterlace_client_install_zmap         "$install_dir" &&
    otterlace_client_install_os           "$install_dir" &&
    true
}

otterlace_client_install() {
    local arch
    # not local: zmap_prefix
    arch="$( uname -m )"

    echo ""
    echo "  client install"
    echo "  intended host: ${otterlace_client_host}"
    echo "  host name: $( hostname )"
    echo "  os name: ${osname}"
    echo "  arch: ${arch}"
    echo "  distro version: $( lsb_release -sc 2>/dev/null || echo 'no release codename' )"

    # zmap_prefix is only meaningful during a client install
    zmap_prefix="${zmap_build}/${osname}_${arch}"
    [ -d "$zmap_prefix" ] || bail "error: client install for ${osname}_${arch} aborted: the ZMap directory ${zmap_prefix} is missing or invalid"

    echo &&
    echo "removing old otterlace installation" &&
    with_new_directory "$otter_home" otterlace_client_install_client &&
    otterlace_script_vars_update "${otter_home}/bin/otterlace_env.sh" &&
    sed -i.bak \
        -e '/^otterlace_installed=/s/=.*$/=true/' \
        "${otter_home}/bin/otterlace" \
        &&
    rm "${otter_home}/bin/otterlace.bak" &&
    (
        zmap="$(     "${otter_home}/bin/zmap"    --version 2>&1 )" || bail "ZMap fail: $zmap"
        seqtools="$( "${otter_home}/bin/blixemh" --version 2>&1 )" || bail "seqtools fail: $seqtools"
        # GNU readlink not available on MacOS, so we use 'cd' and 'pwd -P' instead
        zmap_prefix_real="$( cd "$zmap_prefix" 2>/dev/null && pwd -P || echo ?? )"
        if [ "$zmap_prefix" = "$zmap_prefix_real" ]; then
            is_ln=""
        else
            is_ln=" -> $zmap_prefix_real"
        fi
        write_build_log_entry --level client \
            --zmap_prefix "$zmap_prefix$is_ln" \
            --zmap     "$zmap"     \
            --seqtools "$seqtools"
        ) &&
    echo " [i] finished otterlace_client_install for $otterlace_client_host" &&
    true
}

otterlace_install_all() {
    local env_cmd ssh_cmd fails status

    if [ "$client_build_hosts" = ' ' ]; then
        # This value started off as a quick hack to persuade existing
        # code...  could do better
        echo Building no clients
    elif [ -n "$client_build_hosts" ]; then
        echo ' [W] $client_build_hosts override can (currently) restrict the set of build hosts, but not replace them' >&2
        sleep 1
        # else we would have a local variable
    else
        # choose build hosts to match our zmap build(s)
        client_build_hosts="$( _otterlace_build_config.pl $zmap_trees )" \
            || bail "Bad zmap builds?  No build hosts - no build"
    fi

    otterlace_server_install || fails="server:$?"
    for host in $client_build_hosts; do
        export zmap_build="$( _otterlace_build_config.pl -host $host $zmap_trees )" \
            || bail "No zmap_build for $host ..?"
        env_reexport env_cmd \
            otter_swac otter_nfswub otter_suffix \
            ensembl_otter_root zmap_build build_log
        unset zmap_build

        ssh_cmd="ssh -A $host  env $env_cmd otterlace_client_host=$host  $0"
        printf "\n== Client build: $ssh_cmd\n"
        $ssh_cmd
        status=$?
        if [ "$status" != 0 ]; then
            write_build_log_entry --level client --failed "returned $status"
            fails="$fails${fails:+" "}client,$host:$status"
        fi
    done

    if [ -z "$fails" ]; then
        write_build_log_entry --level all
    else
        write_build_log_entry --level all --failed "$fails"
        ( exit 1 )
    fi
}

write_build_log_entry() {
    local date commit

    date="$( date +'%Y/%m/%d-%H:%M:%S' )"
    commit="$( git rev-list --max-count=1 HEAD )"
    if [ -z "$commit" ]
    then
        commit="NONE"
    fi

    otterlace_build_log_entry \
        -v -l "$build_log" -- \
        --date     "$date"     \
        --version  "$version"  \
        --commit   "$commit"   \
        --builder  "$thisprog" \
        --user     "$( whoami )"      \
        --host     "$( hostname -s )" \
        "$@"
}



setup_self_globals
get_opts_inputvars "$@"
setup_globals
# echo "otter_home = '${otter_home}'" ; exit # uncomment to test


if [ -n "$otterlace_client_host" ]
then
    otterlace_client_install
else
    otterlace_install_all
fi
