#!/bin/bash


# This updates the symbolic links for a given track.


. "$( dirname "$0" )/_otterlace.sh" || exit 1

DRYRUN=''
while [ $# -gt 0 ] && [ "${1:0:1}" = "-" ]; do
    sw=$1
    shift
    case $sw in
        -h | --help)
            bail "Syntax: $0 [ -n | --dry-run ] <track>

 This should be run from an ensembl-otter working copy
 which is up-to-date on the appropriate branch." ;;
        -n | --dry-run)
            echo "(dry run mode)" >&2
            DRYRUN='echo :' ;;
        *) bail "Unknown option $sw" ;;
    esac
done

[ "$#" = 1 ] || bail "Syntax: $0 [ -n | --dry-run ] <track>"
track="$1"

otter_ipath_get holtdir
otter_ipath_get otter_home

[ -d "$otter_home" ] || bail "otter_home=$otter_home: not a directory, will not symlink as $holtdir/otter_${track}"

$DRYRUN ln -vnfs -- "$(basename "$otter_home" )" "$holtdir/otter_${track}"
