# Map the zmap build host to an otterlace build host(s), space
# separated; undef to ignore that build
#
# Pass client_build_hosts=hostname to restrict the selection, but note
# that trying to switch to a different build host will result in
# otterlace_build not knowing which zmap build tree to use.
---
zhost2ohost:
  cbi4a: cbi4a precise-dev64
  cbi4h: cbi4h precise-dev64
  deskpro20407: lucid-dev32
  lucid-dev64: lucid-dev64
  precise-dev64: precise-dev64 trusty-dev64
  mac106229i: ~
  mac18480i: ~
  tviewsrv: lucid-dev32
  deskpro021045: lucid-dev32
  t119-win-build: ~

zmap_build_links_path: ~zmap
ostream2zstream:
  dev:  BUILD.DEVELOPMENT
  test: BUILD.RELEASE
  live: BUILD.PRODUCTION

zhost_osname_override:
  precise-dev64: precise
  trusty-dev64:  precise
