#!/bin/sh


# This script is a CGI wrapper that allows a local web server to run
# the Otterlace CGI scripts.  It relies on the web server to set the
# OTTERLACE_SERVER_ROOT environment variable to the directory
# containing the Otterlace {cgi-bin,data,lib} directories.  (At the
# time of writing this is /nfs/WWWdev/SANGER_docs for the development
# web server.)  If using Apache, put
#
#       SetEnv OTTERLACE_SERVER_ROOT /nfs/WWWdev/SANGER_docs
#
#   in the appropriate <Directory> stanza of httpd.conf.


# the cgi wrapper
cgi_wrapper="$( cd "$( dirname "$0")/.." && pwd )/bin/otterlace_cgi_wrap"

# the CGI script
request_path="$( echo "$REQUEST_URI" | sed -e 's|?.*||' )"
cgi="${OTTERLACE_SERVER_ROOT}/${request_path}"

# exec() the CGI script
exec "$cgi_wrapper" "$cgi" "$QUERY_STRING"

# if we get here, the exec() failed
echo "${0}: failed to exec() ${cgi_wrapper}" >&2
exit 1
