#! /software/bin/perl-5.12.2 -T

use strict;
use warnings;

use CGI;
use YAML qw( LoadFile Dump );

=head1 NAME

pod-link - redirect to requested POD or version control resource

=head1 DESCRIPTION

Quick (dumb) hack to get links to scattered documentation.  Assumes
inputs are package names, but could be extended.  Requires
configuration per module tree.

Should be linked from just one place,
L<http://mediawiki.internal.sanger.ac.uk/wiki/index.php/Template:AnaDoc>
so that it can be moved easily.

Doesn't yet take a "branch or tag" type of arg.

=head1 AUTHOR

Matthew Astley mca@sanger.ac.uk for Anacode

=cut

sub main {
    my %cfg = %{ LoadFile(\*DATA) };
    my $Q = CGI->new;

    # check link in, for non-proliferation
    my $refrr = $Q->referer;
    if ($cfg{referers} && defined $refrr && $refrr !~ $cfg{referers}) {
        print "Status: 403\nContent-Type: text/plain\n\nReferred from $refrr\n
This is not the referrer I expected.\n
This referrer-check protection is intended to avoid accidental
proliferation of links to this transient pod-link URL.\n";
        return ();
    }

    # find relevant links out
    my ($path, $want) = map { $Q->param($_) } qw{ path want };
    $path =~ s{/}{::}g;
    $path =~ s{\.pm$}{};
    my @hit;
    foreach my $ns (@{ $cfg{namespaces} }) {
        my ($nsre, $places) = @$ns;
        push @hit, $ns if $path =~ $nsre && $places->{$want};
    }

    # do substitutions
    my @ln = map { link_subst($path, $_->[1]->{$want}) } @hit;

    # output result
    if (@ln && $want ne 'info') {
        # take first hit
        print $Q->redirect($ln[0]);

    } else {
        my $msg = "I don't know where that is.";
#        $msg = "I don't know which link_out you want." if @ln > 1;
        $msg = "You wanted info:" if $want eq 'info';

        print "Content-Type: text/plain\n\n$msg\n\n".
          "Here is my inline config, your request and the results.\n\n",
            Dump({ cfg => \%cfg, Q => $Q, hit => \@hit,
                   referer => $Q->referer,
                   link_out => \@ln, program => prog_info() });
    }

    return ();
}

sub link_subst {
    my ($path, $place) = @_;
    my ($urlfmt, @subst) = @$place;
    my $upath = $path;
    while (@subst) {
        my ($find, $replace) = splice @subst, 0, 2;
        next if !ref($find) && $find =~ /^#/; # comment on tail
        $upath =~ s{$find}{$replace}g;
    }
    my $url = $urlfmt;
    my $n = $url =~ s{%s}{$upath}g;
    die "Expected one subst in $urlfmt, got $n" unless 1 == $n;
    return $url;
}

sub prog_info {
    $ENV{PATH} = '/bin:/usr/bin';
    delete @ENV{qw{ IFS }};

    my $vsn = qx{git describe --all --always --long --dirty};
    chomp $vsn;

    my $up = qx{git remote show -n origin};

    my %info =
      (script => $0,
       version => $vsn,
       origin => $up);

    return \%info;
}

main();

__DATA__
# Order does matter - first hit wins.
---
namespaces:
  -
    - !!perl/regexp (?-xism:^Bio::EnsEMBL::Pipeline::)
    - vc:
        - http://cvs.sanger.ac.uk/cgi-bin/viewvc.cgi/ensembl-pipeline/modules/%s.pm?root=ensembl&view=log
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://www.ensembl.org/info/docs/Doxygen/pipeline-api/class%s.html
        - !!perl/regexp (?-xism::)
        - _1
  -
    - !!perl/regexp (?-xism:^Bio::EnsEMBL::Analysis::)
    - vc:
        - http://cvs.sanger.ac.uk/cgi-bin/viewvc.cgi/ensembl-analysis/modules/%s.pm?root=ensembl&view=log
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://cvs.sanger.ac.uk/cgi-bin/viewvc.cgi/ensembl-analysis/modules/%s.pm?root=ensembl&content-type=text%2Fplain&view=markup
        - !!perl/regexp (?-xism:::)
        - /
  -
    - !!perl/regexp (?-xism:^AssemblyMapper::)
    - vc:
        - http://cvs.sanger.ac.uk/cgi-bin/viewvc.cgi/ensembl-pipeline/scripts/Finished/assembly/%s.pm?root=ensembl&view=log
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://cvs.sanger.ac.uk/cgi-bin/viewvc.cgi/ensembl-pipeline/scripts/Finished/assembly/%s.pm?root=ensembl&content-type=text%2Fplain&view=markup
        - !!perl/regexp (?-xism:::)
        - /
        - '# nb. alt VC at $iRGA/assembly_mapper.git'
        - '# Doxygen does not cover scripts/'
  -
    - !!perl/regexp (?-xism:^Bio::(Otter|Vega)::|^(Canvas|Edit|MenuCanvas)Window($|::)|^Tk::(ChoiceEditor|ComboBox|DestroyReporter|FBox|HeadedCanvas|HListplusplus|ManualOrder|NoPasteEntry|ObjectPalette|OrderedSelectionFrame|SmartOptionmenu|WrappedOSF|Utils::OnTheFly)$)
    - vc:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/ensembl-otter.git;a=history;f=modules/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - '# omitting h=<file_blobid>'
      pod:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/ensembl-otter.git;a=blob;f=modules/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - '# no POD service, show the text'
  -
    - !!perl/regexp (?-xism:^(t::lib::|Test::Otter|OtterTest)(::|$))
    - vc:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/ensembl-otter.git;a=history;f=modules/t/lib/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - !!perl/regexp (?-xism:^t/lib/)
        - ''
      pod:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/ensembl-otter.git;a=blob;f=modules/t/lib/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - !!perl/regexp (?-xism:^t/lib/)
        - ''
        - '# no POD service, show the text'
  -
    - !!perl/regexp (?-xism:^(Evi|GeneHist|GenomeCanvas|KaryotypeWindow)($|::))
    - vc:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/ensembl-otter.git;a=history;f=tk/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/ensembl-otter.git;a=blob;f=tk/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - '# no POD service, show the text'
  -
    - !!perl/regexp (?-xism:^Bio::EnsEMBL::)
    - vc:
        - http://cvs.sanger.ac.uk/cgi-bin/viewvc.cgi/ensembl/modules/%s.pm?root=ensembl&view=log
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://www.ensembl.org/info/docs/Doxygen/core-api/class%s.html
        - !!perl/regexp (?-xism::)
        - _1
  -
    - !!perl/regexp (?-xism:^Hum::)
    - vc:
        - http://intcvs1.internal.sanger.ac.uk/cgi-bin/viewvc.cgi/PerlModules/%s.pm?root=anacode&view=log
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://intcvs1.internal.sanger.ac.uk/cgi-bin/viewvc.cgi/PerlModules/%s.pm?root=anacode&view=markup
        - !!perl/regexp (?-xism:::)
        - /
  -
    - !!perl/regexp (?-xism:^(SangerWeb|Otter::EnvFix)$)
    - vc:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/webvm.git;a=history;f=lib/devstub/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/webvm.git;a=blob;f=lib/devstub/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - '# no POD service, show the text'
  -
    - !!perl/regexp (?-xism:^(SangerPaths|Otter::.*)$)
    - vc:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/webvm.git;a=history;f=lib/bootstrap/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
      pod:
        - http://git.internal.sanger.ac.uk/cgi-bin/gitweb.cgi?p=anacode/webvm.git;a=blob;f=lib/bootstrap/%s.pm;hb=HEAD
        - !!perl/regexp (?-xism:::)
        - /
        - '# no POD service, show the text'
referers: !!perl/regexp (?i-xsm:^http://(mediawiki|scratchy)\.internal\.sanger\.ac\.uk/(?:wiki/)?index\.php[/?])
