---
file: ~/.ssh/config
mark_start: "# * Automatic: aliases for people's machines"
mark_end: "#<< automatic"
map:
  deskpro-aeb: deskpro20629
  deskpro-af2: deskpro21239
  deskpro-cas: deskpro21242
  deskpro-clb: deskpro20132
  deskpro-cs10: deskpro20122
  deskpro-dm4: deskpro20103
  deskpro-dml: deskpro20111
  deskpro-edgrif: deskpro21152
  deskpro-gdr: deskpro21729
  deskpro-gm5: deskpro101281
  deskpro-gs6: deskpro20623
  deskpro-ib2: deskpro-20111216123429
  deskpro-jel: deskpro20634
  deskpro-jh13: deskpro20622
  deskpro-jla1: deskpro20640
  deskpro-jm12: deskpro20105
  deskpro-jr4: deskpro20116
  deskpro-lr13: deskpro20633
  deskpro-lw2: deskpro20620
  deskpro-mca: deskpro18666
  deskpro-mg13: deskpro18925
  deskpro-mh17: deskpro20407
  deskpro-mh19: deskpro21727
  deskpro-mpk: deskpro102500
  deskpro-mt4: deskpro20129
  deskpro-th2: deskpro20121
  deskpro-vb1: deskpro20127
  mac-gb10: mib103147i
  mac-jgrg: mib19055i
  mac-mg13: mib103146i
