---
file: ~/.ssh/config
mark_start: "# * Automatic: aliases for people's machines"
mark_end: "#<< automatic"
map:
  deskpro-aeb: deskpro20190
  deskpro-af2: deskpro21239
  deskpro-al1: deskpro100806
  deskpro-cas: deskpro21242
  deskpro-clb: deskpro20132
  deskpro-cs10: deskpro20122
  deskpro-dm4: deskpro20103
  deskpro-dml: deskpro20111
  deskpro-edgrif: deskpro21152
  deskpro-erb: deskpro22188
  deskpro-gdr: deskpro21729
  deskpro-gm5: deskpro21269
  deskpro-gs6: deskpro20623
  deskpro-ib2: deskpro20215
  deskpro-jel: deskpro21277
  deskpro-jh13: deskpro20622
  deskpro-jla1: deskpro20640
  deskpro-jm12: deskpro20105
  deskpro-jmg: deskpro18518
  deskpro-jr4: deskpro22010
  deskpro-lr13: deskpro20633
  deskpro-lw2: deskpro20620
  deskpro-mca: deskpro21743
  deskpro-mg13: deskpro20623
  deskpro-mh19: deskpro102484
  deskpro-mpk: deskpro102500
  deskpro-mt4: deskpro20129
  deskpro-th2: deskpro20121
  deskpro-vb1: deskpro20127
  mac-gb10: mib103147i
  mac-jgrg: mib19055i
  mac-mg13: mib103146i
